algoritmo "compras"
// Autor :Arthur Augusto
// Data : 20/10/2020
// Seção de Declarações
var
produtos: vetor[1..10] de CARACTERE
contador: INTEIRO

inicio
para contador de 1 ate 10 faca
  escreval("Informe o produto de n°", contador," da sua lista de compras: ")
  leia(produtos[contador])
fimpara


para contador de 1 ate 10 faca
  escreval("Produto n°", contador," - ", produtos[contador])
fimpara


fimalgoritmo





